import type { Metadata } from "next";
import { Geist, Geist_Mono, Fraunces, Noto_Serif } from "next/font/google";
import "./globals.css";
import Nav from "@/components/layout/Nav/Nav";
import Hero from "@/components/layout/Hero/Hero";
import ShopSection from "@/components/layout/ShopSection/ShopSection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${fraunces.variable} h-full antialiased`}
    >
      <body className="min-h-screen bg-bg text-milk">
        <Nav />
        <Hero />
        <ShopSection />
        {children}
      </body>
    </html>
  );
}
